# Generated by Django 3.2.9 on 2022-05-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_bannerimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerimage',
            options={'ordering': ['-created'], 'verbose_name': 'Картинка для банера', 'verbose_name_plural': 'Картинки для банера'},
        ),
    ]
